version: '3.8'

services:
  airflow-webserver:
    build: ./docker
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8082:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/athlete_db
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - DB_HOST=postgres
      - MONGO_HOST=mongo
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    build: ./docker
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/athlete_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - DB_HOST=postgres
      - MONGO_HOST=mongo
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: athlete_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: athlete_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "athlete_db"]
      interval: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: athlete_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: athlete_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongo:27017/
    depends_on:
      - mongo

  adminer:
    image: adminer
    container_name: athlete_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo

volumes:
  postgres_data:
  mongo_data: